apiVersion: apps/v1
kind: Deployment
metadata:
  name: green2
spec:
  replicas: 4
  template:
    metadata:
      name: blue
      labels:
        app: green
    spec:
      containers:
        - name: cont
          image: httpd
  selector:
    matchLabels:
      app: green
